spring.profiles.active=local

app.password.length=10
app.seed-user-file=users.csv
app.seed-trainee-file=trainees.csv
app.seed-trainer-file=trainers.csv
app.seed-training-file=trainings.csv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.com.epam.gymcrm=DEBUG
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

app.jwt.secret=thisIsATestJwtSecretKeyThatIsLongEnough123
app.jwt.expiration-ms=3600000

spring.security.user.name=

app.security.max-attempts=3
app.security.block-duration-minutes=0
app.security.block-duration-seconds=30


resilience4j.circuitbreaker.instances.workloadService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.workloadService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.workloadService.sliding-window-size=10
resilience4j.circuitbreaker.instances.workloadService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.workloadService.permitted-number-of-calls-in-half-open-state=3

resilience4j.timelimiter.instances.workloadService.timeout-duration=3s

spring.application.name=gym-crm-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

app.workload-service.url=http://trainer-workload-service
app.internal-jwt.secret=thisIsInternalMicroserviceJwtSecretKey12345
app.internal-jwt.expiration-ms=3600000