app.password.length=10
app.seed-user-file=users.csv
app.seed-trainee-file=trainees.csv
app.seed-trainer-file=trainers.csv
app.seed-training-file=trainings.csv

spring.datasource.url=jdbc:h2:mem:gym;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.main.web-application-type=none

logging.level.root=INFO
logging.level.com.epam.gymcrm=DEBUG